### ISSUE TITLE
Mobile Layout Need Help

### ISSUE THREAD

**Issue by timscodebase** [timscodebase/covid#1]
I need help with the Mobile, Tablet layout need help.

Here is a live demo: https://lucid-meitner-b32092.netlify.app/

**Comment by yagopessoa** [comment]
Hey there, I'd like to help with this :)

**Comment by petercr** [comment]
I would also be happy to help out 👍

**Comment by Dave-mash** [comment]
hey @timscodebase I would love to help you out on this

**Comment by timscodebase** [comment]
Thank You for the help David,

Please feel free to fork my repo and submit a pull request.
